# -*- Makefile -*-

lib_TARGETS = champion

# Tu peux rajouter des fichiers sources, headers, ou changer
# des flags de compilation.
champion-srcs = prologin.cc coop_mode.cc solo_mode.cc pathfinding.cc move.cc push.cc closest.cc utils.cc
champion-dists =
champion-cxxflags = -ggdb3 -Wall

# Evite de toucher a ce qui suit
champion-dists += prologin.hh
STECHEC_LANG=cxx
include ../includes/rules.mk
